spring:
  application:
    name: "kafkaavro"
  cloud:
    function:
      definition: produceString;consumerMessage
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            "[key.serializer]": org.apache.kafka.common.serialization.Serdes$StringSerde
            "[value.serializer]": br.com.rafaellino.kafkaavro.serdes.PersonSerde
            "[key.deserializer]": org.apache.kafka.common.serialization.Serdes$StringSerde
            "[value.deserializer]": br.com.rafaellino.kafkaavro.serdes.PersonSerde
      bindings:
        produceString-out-0:
          destination: topic-request-1
          content-type: application/*+avro
          group: producer-group
        consumerMessage-in-0:
          destination: topic-request-1
          content-type: application/*+avro
          group: consumer-group
logging:
  level:
    root: debug
